-- Seeds the catalog from the frontend's former mock data (frontend/src/api/mock/foods.ts)
-- so local menu-service has real content to serve once the frontend switches off mocks.

INSERT INTO menu_items (category_id, name, slug, description, price, spice_level, vegetarian, available, featured, image_url, display_order) VALUES
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Fire Smash Burger', 'fire-smash-burger', 'Double smashed beef patties with melted cheese, pickles, crunchy onions and our signature fire sauce, served in a toasted brioche bun.', 249, 'HOT', false, true, true, '/images/burgers/gourmet-bacon-cheeseburger-close-up.png', 1),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Crispy Chicken Burger', 'crispy-chicken-burger', 'Hand-breaded crispy chicken thigh, house slaw and smoky mayo on a soft milk bun.', 219, 'MEDIUM', false, true, true, '/images/burgers/crispy-spicy-chicken-burger.png', 2),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Double Cheese Smash', 'double-cheese-smash', 'Two smashed patties stacked with double American cheese, grilled onions and burger sauce.', 269, 'MILD', false, true, false, '/images/burgers/gourmet-double-bacon-cheeseburger-cutout.png', 3),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'BBQ Chicken Burger', 'bbq-chicken-burger', 'Grilled chicken breast glazed in smoky BBQ sauce with crispy onions and cheddar.', 239, 'MILD', false, true, false, '/images/burgers/cinematic-gourmet-jalapeno-cheeseburger.png', 4),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Jalapeno Melt', 'jalapeno-melt-burger', 'Spicy chicken patty loaded with pickled jalapenos, pepper jack cheese and chipotle mayo.', 249, 'HOT', false, true, false, '/images/burgers/cinematic-gourmet-jalapeno-cheeseburger.png', 5),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Peri Peri Burger', 'peri-peri-burger', 'Flame-grilled peri peri chicken thigh with lime slaw and peri mayo.', 259, 'HOT', false, true, false, '/images/burgers/crispy-spicy-chicken-burger.png', 6),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Spicy Paneer Burger', 'spicy-paneer-burger', 'Crispy spiced paneer steak with mint mayo, tomato and iceberg lettuce.', 219, 'MEDIUM', true, true, false, '/images/burgers/gourmet-bacon-cheeseburger-close-up.png', 7),
((SELECT id FROM categories WHERE code = 'BURGERS'), 'Loaded Cheese Burger', 'loaded-cheese-burger', 'Beef patty piled with nacho cheese, jalapenos, crispy onions and hot sauce drizzle.', 279, 'HOT', false, true, false, '/images/burgers/gourmet-double-bacon-cheeseburger-cutout.png', 8),

((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Nashville Hot Chicken', 'nashville-hot-chicken', 'Crispy fried chicken thigh soaked in Nashville hot oil, pickles and toasted bun on the side.', 259, 'EXTRA_HOT', false, true, true, '/images/chicken-fingers/spicy-glazed-chicken-wings-with-chilli-and-herbs.png', 1),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Fire Wings', 'fire-wings', 'Double-fried chicken wings tossed in our fire glaze, served with ranch dip.', 229, 'HOT', false, true, true, '/images/chicken-fingers/spicy-glazed-chicken-wings-with-chilli-and-herbs.png', 2),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Crispy Chicken Bucket', 'crispy-chicken-bucket', '8 pieces of our signature crispy fried chicken, hot and fresh out of the fryer.', 549, 'MEDIUM', false, true, false, '/images/chicken-fingers/spicyeat-crispy-chicken-feast.png', 3),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Chicken Tenders', 'chicken-tenders', 'Hand-breaded chicken tenders, extra crispy, served with spicy dip.', 199, 'MILD', false, true, false, '/images/chicken-fingers/crispy-chicken-tenders-with-spicy-dip.png', 4),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Chicken Popcorn', 'chicken-popcorn', 'Bite-sized crispy chicken popcorn tossed in a spiced coating.', 179, 'MEDIUM', false, true, false, '/images/chicken-fingers/crispy-spiced-chicken-popcorn-with-dip.png', 5),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Spicy Chicken Bites', 'spicy-chicken-bites', 'Juicy marinated chicken bites, fried crisp and finished with chilli flakes.', 189, 'HOT', false, true, false, '/images/chicken-fingers/crispy-chicken-tenders-with-spicy-dip.png', 6),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Garlic Butter Wings', 'garlic-butter-wings', 'Crispy wings tossed in roasted garlic butter and fresh herbs.', 229, 'MILD', false, true, false, '/images/chicken-fingers/spicy-glazed-chicken-wings-with-chilli-and-herbs.png', 7),
((SELECT id FROM categories WHERE code = 'FRIED_CHICKEN'), 'Loaded Chicken Box', 'loaded-chicken-box', 'Crispy chicken, fries, coleslaw and a dip all boxed up together.', 329, 'MEDIUM', false, true, false, '/images/chicken-fingers/spicyeat-crispy-chicken-feast.png', 8),

((SELECT id FROM categories WHERE code = 'PIZZA'), 'Fire Chicken Pizza', 'fire-chicken-pizza', 'Fire-glazed chicken, jalapenos and mozzarella on our signature stretchy crust.', 349, 'HOT', false, true, true, '/images/pizza/stretchy-pepperoni-supreme-pizza-feast.png', 1),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'BBQ Chicken Pizza', 'bbq-chicken-pizza', 'Smoky BBQ chicken, red onions and mozzarella on a hand-tossed base.', 349, 'MILD', false, true, true, '/images/pizza/cheesy-pepperoni-pizza-pull.png', 2),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Pepperoni Pizza', 'pepperoni-pizza', 'Loaded pepperoni and a stretchy blanket of mozzarella cheese.', 329, 'MEDIUM', false, true, false, '/images/pizza/stretchy-pepperoni-pizza-delight.png', 3),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Four Cheese Pizza', 'four-cheese-pizza', 'Mozzarella, cheddar, parmesan and pepper jack come together in one cheese pull.', 339, 'MILD', true, true, false, '/images/pizza/pizza-3.png', 4),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Jalapeno Melt Pizza', 'jalapeno-melt-pizza', 'Pickled jalapenos, extra cheese and a chilli oil drizzle.', 339, 'HOT', true, true, false, '/images/pizza/pizza-4.png', 5),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Classic Margherita', 'classic-margherita', 'San Marzano tomato sauce, fresh mozzarella and basil.', 279, 'MILD', true, true, false, '/images/pizza/pizza-5.png', 6),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Loaded Chicken Pizza', 'loaded-chicken-pizza', 'Double chicken, extra cheese and a hit of fire sauce on top.', 379, 'MEDIUM', false, true, false, '/images/pizza/stretchy-pepperoni-supreme-pizza-feast.png', 7),
((SELECT id FROM categories WHERE code = 'PIZZA'), 'Veggie Supreme', 'veggie-supreme', 'Bell peppers, olives, onions, mushroom and mozzarella on a hand-tossed base.', 309, 'MILD', true, true, false, '/images/pizza/pizza-3.png', 8),

((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'Crispy Chicken Wrap', 'crispy-chicken-wrap', 'Crispy chicken strips, lettuce and smoky mayo rolled in a warm tortilla.', 199, 'MEDIUM', false, true, true, '/images/wraps/grilled-chicken-wraps-with-fresh-filling.png', 1),
((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'Fire Chicken Roll', 'fire-chicken-roll', 'Fire-glazed chicken, pickled onions and chilli mayo in a soft roll.', 209, 'HOT', false, true, false, '/images/wraps/grilled-chicken-wraps-with-fresh-fillings.png', 2),
((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'BBQ Chicken Wrap', 'bbq-chicken-wrap', 'Smoky BBQ chicken, slaw and cheddar rolled up tight.', 199, 'MILD', false, true, false, '/images/wraps/grilled-chicken-wraps-with-fresh-filling.png', 3),
((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'Peri Peri Wrap', 'peri-peri-wrap', 'Peri peri chicken, lettuce and lime mayo in a warm flour tortilla.', 209, 'HOT', false, true, false, '/images/wraps/grilled-chicken-wraps-with-fresh-fillings.png', 4),
((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'Paneer Tikka Wrap', 'paneer-tikka-wrap', 'Char-grilled paneer tikka, onions and mint chutney rolled together.', 189, 'MEDIUM', true, true, false, '/images/wraps/grilled-chicken-wraps-with-fresh-filling.png', 5),
((SELECT id FROM categories WHERE code = 'WRAPS_ROLLS'), 'Loaded Cheese Wrap', 'loaded-cheese-wrap', 'Crispy chicken, nacho cheese sauce and jalapenos in one loaded wrap.', 219, 'MEDIUM', false, true, false, '/images/wraps/grilled-chicken-wraps-with-fresh-fillings.png', 6),

((SELECT id FROM categories WHERE code = 'LOADED'), 'Loaded Cheese Fries', 'loaded-cheese-fries', 'Crispy fries drowned in nacho cheese sauce and a chilli drizzle.', 179, 'MEDIUM', true, true, true, '/images/pasta/loaded.png', 1),
((SELECT id FROM categories WHERE code = 'LOADED'), 'Fire Chicken Fries', 'fire-chicken-fries', 'Loaded fries topped with fire chicken bites and spicy mayo.', 219, 'HOT', false, true, false, '/images/pasta/loaded.png', 2),
((SELECT id FROM categories WHERE code = 'LOADED'), 'Chicken Nachos', 'chicken-nachos', 'Crispy nachos piled with spiced chicken, cheese sauce and jalapenos.', 229, 'MEDIUM', false, true, false, '/images/sides/crispy-onion-rings-with-spicy-aioli.png', 3),
((SELECT id FROM categories WHERE code = 'LOADED'), 'Crispy Sharing Box', 'crispy-sharing-box', 'A mix of tenders, wings and fries built for sharing (or not).', 399, 'MEDIUM', false, true, false, '/images/sides/rustic-golden-fries-with-ketchup.png', 4),
((SELECT id FROM categories WHERE code = 'LOADED'), 'Mozzarella Sticks', 'mozzarella-sticks', 'Golden fried mozzarella sticks with a marinara dip.', 189, 'MILD', true, true, false, '/images/sides/crispy-onion-rings-with-spicy-aioli.png', 5),
((SELECT id FROM categories WHERE code = 'LOADED'), 'Onion Rings Deluxe', 'onion-rings-deluxe', 'Thick-cut onion rings, beer-battered and fried to a crisp.', 169, 'MILD', true, true, false, '/images/sides/crispy-onion-rings-with-spicy-aioli.png', 6),

((SELECT id FROM categories WHERE code = 'PASTA'), 'Chicken Alfredo', 'chicken-alfredo', 'Grilled chicken tossed in a rich creamy alfredo sauce with parmesan.', 289, 'MILD', false, true, true, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 1),
((SELECT id FROM categories WHERE code = 'PASTA'), 'Fire Arrabbiata', 'fire-arrabbiata', 'Penne tossed in a fiery tomato arrabbiata sauce with chilli flakes.', 269, 'HOT', true, true, false, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 2),
((SELECT id FROM categories WHERE code = 'PASTA'), 'Pink Sauce Chicken', 'pink-sauce-chicken', 'Grilled chicken in a blend of creamy and tomato pink sauce.', 289, 'MEDIUM', false, true, false, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 3),
((SELECT id FROM categories WHERE code = 'PASTA'), 'Four Cheese Pasta', 'four-cheese-pasta', 'Penne baked in a blend of four melted cheeses.', 279, 'MILD', true, true, false, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 4),
((SELECT id FROM categories WHERE code = 'PASTA'), 'Spicy Grilled Chicken Pasta', 'spicy-grilled-chicken-pasta', 'Grilled chicken and penne tossed in a spicy tomato basil sauce.', 299, 'HOT', false, true, false, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 5),
((SELECT id FROM categories WHERE code = 'PASTA'), 'Creamy Veg Pasta', 'creamy-veg-pasta', 'Seasonal vegetables tossed in a light creamy white sauce.', 249, 'MILD', true, true, false, '/images/pasta/creamy-chicken-alfredo-pasta-bowl.png', 6),

((SELECT id FROM categories WHERE code = 'SIDES'), 'Classic Fries', 'classic-fries', 'Golden fried, lightly salted, always crispy.', 99, 'MILD', true, true, false, '/images/sides/rustic-golden-fries-with-ketchup.png', 1),
((SELECT id FROM categories WHERE code = 'SIDES'), 'Peri Peri Fries', 'peri-peri-fries', 'Crispy fries tossed in a spiced peri peri seasoning.', 119, 'MEDIUM', true, true, true, '/images/sides/crispy-herb-seasoned-potato-wedges.png', 2),
((SELECT id FROM categories WHERE code = 'SIDES'), 'Cheese Fries', 'cheese-fries', 'Fries smothered in a warm cheese sauce.', 139, 'MILD', true, true, false, '/images/sides/rustic-golden-fries-with-ketchup.png', 3),
((SELECT id FROM categories WHERE code = 'SIDES'), 'Garlic Bread', 'garlic-bread', 'Toasted bread brushed with roasted garlic butter.', 99, 'MILD', true, true, false, '/images/sides/glistening-herb-garlic-toast-on-dark-plate.png', 4),
((SELECT id FROM categories WHERE code = 'SIDES'), 'Cheese Garlic Bread', 'cheese-garlic-bread', 'Garlic bread loaded with a blanket of melted mozzarella.', 129, 'MILD', true, true, false, '/images/sides/glistening-herb-garlic-toast-on-dark-plate.png', 5),
((SELECT id FROM categories WHERE code = 'SIDES'), 'Onion Rings', 'onion-rings', 'Crispy battered onion rings served with spicy aioli.', 109, 'MILD', true, true, false, '/images/sides/crispy-onion-rings-with-spicy-aioli.png', 6),

((SELECT id FROM categories WHERE code = 'DESSERTS'), 'Chocolate Lava Cake', 'chocolate-lava-cake', 'Warm chocolate cake with a molten center, served with vanilla ice cream.', 149, 'MILD', true, true, true, '/images/desserts/molten-chocolate-lava-cake-delight.png', 1),
((SELECT id FROM categories WHERE code = 'DESSERTS'), 'Brownie & Ice Cream', 'brownie-and-ice-cream', 'Fudgy chocolate brownie served warm with a scoop of vanilla ice cream.', 159, 'MILD', true, true, false, '/images/desserts/dessert.png', 2),
((SELECT id FROM categories WHERE code = 'DESSERTS'), 'New York Cheesecake', 'new-york-cheesecake', 'Rich, creamy baked cheesecake topped with a fresh berry compote.', 169, 'MILD', true, true, false, '/images/desserts/rustic-berry-topped-cheesecake-slice.png', 3),
((SELECT id FROM categories WHERE code = 'DESSERTS'), 'Chocolate Mousse', 'chocolate-mousse', 'Light and airy dark chocolate mousse, chilled to perfection.', 139, 'MILD', true, true, false, '/images/desserts/decadent-chocolate-ganache-cake.png', 4),
((SELECT id FROM categories WHERE code = 'DESSERTS'), 'Cookie Skillet', 'cookie-skillet', 'A warm skillet cookie topped with ice cream and chocolate drizzle.', 179, 'MILD', true, true, false, '/images/desserts/tiramisu.png', 5);
