CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE carts (
    user_id    UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
